long_name = "Glutton"
short_name = "glutton"
for_module = "tome"
version = {1,2,3}
weight = 100
author = {"desophos"}
homepage = "https://github.com/desophos/tome-glutton"
description = "Glutton class"
tags = {"class"}
overload = true
superload = true
hooks = true
data = true
